### ISSUE TITLE
break styles improvement discussion

### ISSUE THREAD

**Issue by haubourg** [Oslandia/labelconnector#12]
Break style currently leads to sometimes weird lines going backwards compared to old easycustomlabeling style:

![image](https://user-images.githubusercontent.com/1629853/58458650-08eefb80-812a-11e9-99ba-1629773cdeed.png)

That should probably be improved still I'd like to hear about user's preferences 

Easy custom labeling always forced a '45°' heading for the line start, so that all connectors end to be aligned, making a more tidy view. Label connector computes a break at half length of the connector thus leading to different angles between connectors

![image](https://user-images.githubusercontent.com/1629853/58459024-c7128500-812a-11e9-94af-3dc9f0857dad.png)

**Comment by FERRATON** [comment]
fully agree
I think users like the Easycustom labelling style, it should be one of the available styles.

**Comment by lbartoletti** [comment]
We can add as many styles as we want. It is therefore possible to add variants on styles such as broken lines for example.

**Comment by haubourg** [comment]
@lbartoletti I will have a look at the expression

**Comment by haubourg** [comment]
Old label breaks are back with 9d069ba
I had to push a very loong conditional expression so that we don't depend on a function that couldn't be shared easily in other projects or QGIS installs
