### ISSUE TITLE
Some layers require a signal in label properties to display labels

### ISSUE THREAD

**Issue by haubourg** [Oslandia/labelconnector#13]
tested with a line layers,  applying the style result in no label displayed until I modify the labeling properties. A signal is not cast somewhere, but not for all kinds of layers. 

see the screencast: 

![label_connector_refresh_label_properties_bug](https://user-images.githubusercontent.com/1629853/58495585-29de3d80-8178-11e9-97cb-3ed1e460b86c.gif)

The qml for this file : 
[line.zip](https://github.com/Oslandia/labelconnector/files/3228758/line.zip)

**Comment by lbartoletti** [comment]
I opened an issue on qgis

**Comment by haubourg** [comment]
here: https://github.com/qgis/QGIS/issues/30046
