### ISSUE TITLE
Move labels doesn't work with GPKG

### ISSUE THREAD

**Issue by haubourg** [Oslandia/labelconnector#16]
It is probably an upstream issue in QGIS 3.4.9 - probably a regression

**Comment by lbartoletti** [comment]
Confirmed in 3.4.7

**Comment by haubourg** [comment]
@pblottiere it seems to be a QGIS issue. Does that ring any bell to you ?

**Comment by pblottiere** [comment]
@haubourg I just tried on master and everything works fine with and without auxiliary storage.

Can you describe your procedure please?

**Comment by haubourg** [comment]
@pblottiere just tested with master, it works nicely too. The issue seems to be in 3.4 only

**Comment by haubourg** [comment]
just tested 3.8 - no issue

**Comment by lbartoletti** [comment]
Since QGIS 3.4 is the LTR, @pblottiere it should be fixed?

**Comment by pblottiere** [comment]
>  it should be fixed?

@lbartoletti  Yes I think so. Can you open an issue and assign it to me please?

**Comment by lbartoletti** [comment]
@pblottiere have fun https://github.com/qgis/QGIS/issues/30408 :)

**Comment by FERRATON** [comment]
Même avec QGIS 3.8 si on déplace par exemple l'étiquette LE BAILLEUL alors plusieurs autres étiquettes se déplacent  intempestivement.
![2019-06-26_15h01_46](https://user-images.githubusercontent.com/2129643/60181859-6d81a100-9823-11e9-8f37-0e11433f9010.png)

**Comment by haubourg** [comment]
@FERRATON ça c'est un autre problème je pense. Tu utilise bien un `id` réellement unique au moment de la création de la table auxiliaire ?

**Comment by haubourg** [comment]
@FERRATON ceci dit, c'est possible que ce soit lié, je pense que le comportement interne des fid - id de QGIS a été changé récemment, et peut varier selon les versions de GDAL. On regarde ça dans le ticket QGIS . Je ferme celui ci coté plugin, c'est indépendant
