### ISSUE TITLE
marge entre le trait de rappel et l'étiquette

### ISSUE THREAD

**Issue by FERRATON** [Oslandia/labelconnector#18]
Easy Custom labelling laissait une marche entre le trait de rappel et l'étiquette. Cette petite marge serait à reprendre.
![2019-06-26_14h35_45](https://user-images.githubusercontent.com/2129643/60180312-07dfe580-9820-11e9-8a26-0ceb6baf7765.png)

**Comment by haubourg** [comment]
@FERRATON En fait c'était un tampon, ça te va comme solution de mettre un tampon par défaut ?

**Comment by FERRATON** [comment]
A priori oui.

**Comment by lbartoletti** [comment]
J'ai ajouté le buffer https://github.com/Oslandia/labelconnector/commit/f295afdd1ad4f11938fed9ff8490bcff019757de

On peut également paramétrer le style si vous souhaitez.

**Comment by FERRATON** [comment]
Oui, çà serait un plus. merci.

**Comment by FERRATON** [comment]
En fait avec EasyCustomLabelling, c'était un fond rectangle 'taille selon tampon' de x=0.2, y=0.2 qui était utilisé. Je pense qu'il faut effectivement que l'utilisation d'un tampon et/ou d'un fond rectangle soit un paramètre car sinon on modifie l'apparence de toutes les étiquettes ce qui n'est pas forcement ce qui est désiré par l'utilisateur.

**Comment by haubourg** [comment]
> En fait avec EasyCustomLabelling, c'était un fond rectangle 'taille selon tampon' de x=0.2, y=0.2 qui était utilisé. Je pense qu'il faut effectivement que l'utilisation d'un tampon et/ou d'un fond rectangle soit un paramètre car sinon on modifie l'apparence de toutes les étiquettes ce qui n'est pas forcement ce qui est désiré par l'utilisateur.

Ok, je rajoute l'expression pour cela.
