### ISSUE TITLE
Changer le style de connecteur plus simplement

### ISSUE THREAD

**Issue by FERRATON** [Oslandia/labelconnector#19]
Actuellement si on souhaite changer le style de connecteur il faut d'abord supprimer manuellement le générateur de géométrie de l'ancien connecteur dans le style. Ne serait-il pas possible de poser la question à l'utilisateur en cas de lancement une 2ème fois de labelconnector, puis le cas échéant de supprimer par programme l'ancien générateur, plutôt que d'afficher un message lui demandant de le faire manuellement ?

**Comment by haubourg** [comment]
@lbartoletti la spécification était d'écraser le style entre les balises. C'est une régression du coup. Tu peux regarder s'il te plaît?

**Comment by lbartoletti** [comment]
@haubourg non, on avait dit que - pour éviter les erreurs de manipulation de la part des utilisateurs - il fallait enlever les commentaires dans le code de la géométrie. Si le plugin trouve la balise alors il affiche l'avertissement, sinon, il écrase le code de la géométrie.

**Comment by lbartoletti** [comment]
Mais on peut envisager d'afficher un dialogue donnant le choix à l'utilisateur.

**Comment by lbartoletti** [comment]
J'ai ajouté une boîte de dialogue si on détecte une géométrie générée par le plugin dans c10bb9f
