### ISSUE TITLE
Elbow connector style

### ISSUE THREAD

**Issue by haubourg** [Oslandia/labelconnector#2]
We have this style: 
![image](https://user-images.githubusercontent.com/1629853/57940847-a5fd9900-78cd-11e9-9775-10b82901393a.png)

we need this style like in former EasyCustomLabeling plugin 
![image](https://user-images.githubusercontent.com/1629853/57940897-c4fc2b00-78cd-11e9-82d8-97540e3eabf9.png)

**Comment by lbartoletti** [comment]
For now, there are 3 styles. Elbow, line and break. Break is the nearest style from the former plugin.

**Comment by haubourg** [comment]
Yep, now I see it, sorry for the noise
