### ISSUE TITLE
Callouts lines can be drawn underneath features

### ISSUE THREAD

**Issue by FERRATON** [Oslandia/labelconnector#20]
Les traits de rappels peuvent être en-dessous de certaines entités.
Ce pb peut être résolu en activant le niveau de symbole dans les paramètres avancés.
Il serait bien que le plugin active automatiquement ce paramètre.
![cgbdohnbigdfelkl](https://user-images.githubusercontent.com/2129643/60420247-886b6100-9be7-11e9-83af-e3614dc1147d.png)
[n_epci_zsup_r52.zip](https://github.com/Oslandia/labelconnector/files/3344482/n_epci_zsup_r52.zip)

**Comment by haubourg** [comment]
@lbartoletti est-ce que c'est simple ou complexe à réaliser?

**Comment by haubourg** [comment]
@FERRATON j'ai amélioré la doc dans https://github.com/Oslandia/labelconnector/commit/7c95b4691fe0ee5081820ab098e8aad01fba5aca
