### ISSUE TITLE
Icônes surchargées dans la légende avec une analyse graduée

### ISSUE THREAD

**Issue by FERRATON** [Oslandia/labelconnector#21]
Si on active LabelConnector après une analyse graduées. Les icônes sont surchargées par le symbole du trait de rappel.
![Label connector gradué-2](https://user-images.githubusercontent.com/2129643/60424662-1ef05000-9bf1-11e9-9751-4b9d5a946a82.PNG)

Ce qui n'est pas souhaitable.

Ce n'est pas le cas si on transforme le style gradué en ensemble de règles.
![Label connector ensemble de règles](https://user-images.githubusercontent.com/2129643/60424907-a63dc380-9bf1-11e9-949d-92b517d0ac91.PNG)

**Comment by haubourg** [comment]
@FERRATON Ce n'est pas possible de changer ce comportement avec un simple plugin. Cela relève du portage dans le core de QGIS.

**Comment by FERRATON** [comment]
OK. A indiquer au minimum dans la documentation et l'aide.
Il faut passer le style gradué en ensemble de règles avant d'utiliser labelconnector pour un résultat correct.

**Comment by haubourg** [comment]
@FERRATON  c'est fait dans 7c95b4691fe0ee5081820ab098e8aad01fba5aca
