### ISSUE TITLE
version FR vs version US

### ISSUE THREAD

**Issue by FERRATON** [Oslandia/labelconnector#23]
Les textes des boites de dialogue sont en anglais même si l'interface de QGIS est paramétré en français.
La traduction Anglais/français (fichier metadata.txt) de la phrase de présentation du plugin n'est pas tout à fait équivalente. 
La version anglaise 
'This plugin creates label connector (line from centroid to the label)'
n'indique pas clairement que les connecteur ne sont créés que pour les étiquettes déplacés manuellement.

**Comment by haubourg** [comment]
@lbartoletti  tu peux prendre ça?

**Comment by lbartoletti** [comment]
J'ai mis à jour le fichier de traduction

**Comment by lbartoletti** [comment]
> n'indique pas clairement que les connecteur ne sont créés que pour les étiquettes déplacés manuellement.

Le connecteur est crée, mais visible seulement si l'étiquette est éloignée du point d'origine. 

@haubourg @FERRATON votre préférence va sur la version FR ou US ?

**Comment by FERRATON** [comment]
Oui les connecteurs sont effectivement créés mais non visibles tant que l'on ne déplace pas au moins une étiquette... c'est un utilisateur qui m'a fait cette remarque en pensant que les connecteurs apparaîtraient dès l'appui sur le bouton.  J'ai donc une préférence pour la version FR.

**Comment by lbartoletti** [comment]
Fait dans https://github.com/Oslandia/labelconnector/commit/15043911335348f07095fb786ba0d4cffa8f386a
