### ISSUE TITLE
Label settings not applied correctly when source layer is not labeled

### ISSUE THREAD

**Issue by haubourg** [Oslandia/labelconnector#24]
When applying label connector to a a layer with no label, the labeling toolbar does not activate itself. I have to play with the settings and then this triggers the activation of the labeling toolbar. 
I suspect we need to emit some signal in that case to activate the toolbar.

**Comment by lbartoletti** [comment]
Right, you have to reselect the active layer (when you have two layers, select another and reselect the current layer). It is present on some QGIS tools, not especially with this plugin. I'll take a look.
